version: 1.7f.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
image: Visual Studio 2017
configuration: 
 - Debug
 - Mixed
 - Release
platform: x64
build:
  project: code/xrEngine.sln
  publish_wap: true
  parallel: true
  verbosity: quiet
before_build:
- cmd: >-
    copy /Y code\engine.vc2008\xrCore\GitParser\hackappveyor.inl code\engine.vc2008\xrCore\GitParser\hack.appveyor
after_build:
- cmd: >-
    copy code\SDK\binaries\x64\amd_ags_x64.dll game\bins\
    
    cd binaries\x64\Release
    
    copy *.dll ..\..\..\game\bins
    
    copy *.exe ..\..\..\game\bins
    
    cd ..\..\..\
    
    7z a xrOxygen.7z .\game
    
    echo appveyor PushArtifact xrOxygen.7z Release
    
    appveyor PushArtifact xrOxygen.7z
    
artifacts:
- path: .\xrOxygen.7z
  name: Release
deploy:
- provider: GitHub
  auth_token:
    secure: 1OAwfSrwEQtGa28QEVVJhqs4SQH/9nfoiUnL04rBkGCjuP+3mJIWTg1Usmle6mP/
  repository: xrOxygen/xray-oxygen
  artifact: Release
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true
    Dep: Test
